export const symptoms = [
{ "value": "back_pain", "label": "Back Pain" }, 
{ "value": "constipation", "label": "Constipation" }, 
{ "value": "abdominal_pain", "label": "Abdominal Pain" }, 
{ "value": "diarrhoea", "label": "Diarrhoea" }, 
{ "value": "mild_fever", "label": "Mild Fever" }, 
{ "value": "yellow_urine", "label": "Yellow Urine" }, 
{ "value": "yellowing_of_eyes", "label": "Yellowing Of Eyes" }, 
{ "value": "acute_liver_failure", "label": "Acute Liver Failure" }, 
{ "value": "swelling_of_stomach", "label": "Swelling Of Stomach" }, 
{ "value": "swelled_lymph_nodes", "label": "Swelled Lymph Nodes" }, 
{ "value": "malaise", "label": "Malaise" }, 
{ "value": "blurred_and_distorted_vision", "label": "Blurred And Distorted Vision" }, 
{ "value": "phlegm", "label": "Phlegm" }, 
{ "value": "throat_irritation", "label": "Throat Irritation" }, 
{ "value": "redness_of_eyes", "label": "Redness Of Eyes" }, 
{ "value": "sinus_pressure", "label": "Sinus Pressure" }, 
{ "value": "runny_nose", "label": "Runny Nose" }, 
{ "value": "congestion", "label": "Congestion" }, 
{ "value": "chest_pain", "label": "Chest Pain" }, 
{ "value": "weakness_in_limbs", "label": "Weakness In Limbs" }, 
{ "value": "fast_heart_rate", "label": "Fast Heart Rate" }, 
{ "value": "pain_during_bowel_movements", "label": "Pain During Bowel Movements" }, 
{ "value": "pain_in_anal_region", "label": "Pain In Anal Region" }, 
{ "value": "bloody_stool", "label": "Bloody Stool" }, 
{ "value": "irritation_in_anus", "label": "Irritation In Anus" }, 
{ "value": "neck_pain", "label": "Neck Pain" }, 
{ "value": "dizziness", "label": "Dizziness" }, 
{ "value": "cramps", "label": "Cramps" }, 
{ "value": "bruising", "label": "Bruising" }, 
{ "value": "obesity", "label": "Obesity" }, 
{ "value": "swollen_legs", "label": "Swollen Legs" }, 
{ "value": "swollen_blood_vessels", "label": "Swollen Blood Vessels" }, 
{ "value": "puffy_face_and_eyes", "label": "Puffy Face And Eyes" }, 
{ "value": "enlarged_thyroid", "label": "Enlarged Thyroid" }, 
{ "value": "brittle_nails", "label": "Brittle Nails" }, 
{ "value": "swollen_extremeties", "label": "Swollen Extremeties" }, 
{ "value": "excessive_hunger", "label": "Excessive Hunger" }, 
{ "value": "extra_marital_contacts", "label": "Extra Marital Contacts" }, 
{ "value": "drying_and_tingling_lips", "label": "Drying And Tingling Lips" }, 
{ "value": "slurred_speech", "label": "Slurred Speech" }, 
{ "value": "knee_pain", "label": "Knee Pain" }, 
{ "value": "hip_joint_pain", "label": "Hip Joint Pain" }, 
{ "value": "muscle_weakness", "label": "Muscle Weakness" }, 
{ "value": "stiff_neck", "label": "Stiff Neck" }, 
{ "value": "swelling_joints", "label": "Swelling Joints" }, 
{ "value": "movement_stiffness", "label": "Movement Stiffness" }, 
{ "value": "spinning_movements", "label": "Spinning Movements" }, 
{ "value": "loss_of_balance", "label": "Loss Of Balance" }, 
{ "value": "unsteadiness", "label": "Unsteadiness" }, 
{ "value": "weakness_of_one_body_side", "label": "Weakness Of One Body Side" }, 
{ "value": "loss_of_smell", "label": "Loss Of Smell" }, 
{ "value": "bladder_discomfort", "label": "Bladder Discomfort" }, 
{ "value": "foul_smell_of urine", "label": "Foul Smell Of Urine" }, 
{ "value": "continuous_feel_of_urine", "label": "Continuous Feel Of Urine" }, 
{ "value": "passage_of_gases", "label": "Passage Of Gases" }, 
{ "value": "internal_itching", "label": "Internal Itching" }, 
{ "value": "toxic_look_(typhos)", "label": "Toxic Look (typhos)" }, 
{ "value": "depression", "label": "Depression" }, 
{ "value": "irritability", "label": "Irritability" }, 
{ "value": "muscle_pain", "label": "Muscle Pain" }, 
{ "value": "altered_sensorium", "label": "Altered Sensorium" }, 
{ "value": "red_spots_over_body", "label": "Red Spots Over Body" }, 
{ "value": "belly_pain", "label": "Belly Pain" }, 
{ "value": "abnormal_menstruation", "label": "Abnormal Menstruation" }, 
{ "value": "dischromic _patches", "label": "Dischromic  Patches" }, 
{ "value": "watering_from_eyes", "label": "Watering From Eyes" }, 
{ "value": "increased_appetite", "label": "Increased Appetite" }, 
{ "value": "polyuria", "label": "Polyuria" }, 
{ "value": "family_history", "label": "Family History" }, 
{ "value": "mucoid_sputum", "label": "Mucoid Sputum" }, 
{ "value": "rusty_sputum", "label": "Rusty Sputum" }, 
{ "value": "lack_of_concentration", "label": "Lack Of Concentration" }, 
{ "value": "visual_disturbances", "label": "Visual Disturbances" }, 
{ "value": "receiving_blood_transfusion", "label": "Receiving Blood Transfusion" }, 
{ "value": "receiving_unsterile_injections", "label": "Receiving Unsterile Injections" }, 
{ "value": "coma", "label": "Coma" }, 
{ "value": "stomach_bleeding", "label": "Stomach Bleeding" }, 
{ "value": "distention_of_abdomen", "label": "Distention Of Abdomen" }, 
{ "value": "history_of_alcohol_consumption", "label": "History Of Alcohol Consumption" }, 
{ "value": "fluid_overload", "label": "Fluid Overload" }, 
{ "value": "blood_in_sputum", "label": "Blood In Sputum" }, 
{ "value": "prominent_veins_on_calf", "label": "Prominent Veins On Calf" }, 
{ "value": "palpitations", "label": "Palpitations" }, 
{ "value": "painful_walking", "label": "Painful Walking" }, 
{ "value": "pus_filled_pimples", "label": "Pus Filled Pimples" }, 
{ "value": "blackheads", "label": "Blackheads" }, 
{ "value": "scurring", "label": "Scurring" }, 
{ "value": "skin_peeling", "label": "Skin Peeling" }, 
{ "value": "silver_like_dusting", "label": "Silver Like Dusting" }, 
{ "value": "small_dents_in_nails", "label": "Small Dents In Nails" }, 
{ "value": "inflammatory_nails", "label": "Inflammatory Nails" }, 
{ "value": "blister", "label": "Blister" }, 
{ "value": "red_sore_around_nose", "label": "Red Sore Around Nose" }, 
{ "value": "yellow_crust_ooze", "label": "Yellow Crust Ooze" }
]